version: '3.9'
services:
  frontend:
    build: ./frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - "0:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/jobtracker
    depends_on:
      - db
    volumes:
      - ./backend/app:/app/app  # hot-reload FastAPI app
      - ./backend/alembic:/app/alembic

  db:
    image: postgres:15
    restart: always
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobtracker
